### ISSUE TITLE
Sentry + Moodle plugin for production?

### ISSUE THREAD

**Issue by rayronvictor** [LdesignMedia/moodle-tool_developer#1]
Hi @luukverhoeven!

Why shouldn't this plugin be used in production? Is it due to the Sentry?

A plugin integrating Moodle and Sentry for production would be awesome!
Are you thinking of creating a specific plugin for this purpose and uploading it to the official plugin repository? https://docs.moodle.org/dev/Plugin_contribution

**Comment by luukverhoeven** [comment]
@rayronvictor Currently, we do not intend to upload this plugin to Moodle.org. The primary reason is that it will be used within our internal development environments, and our focus is on developing this plugin specifically for developers.

Integrating Sentry support could potentially be implemented as a separate plugin. Indeed, an official Moodle plugin would be a valuable addition to the community plugins. However, we are not currently partnered with Sentry and do not have the financial resources to develop this plugin at this time.

**Comment by rayronvictor** [comment]
@luukverhoeven thanks for the quickly response!
